default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: todo_sample
  password: todo_sample_pw
  host: mysql

development:
  <<: *default
  database: todo_sample_development

test:
  <<: *default
  database: todo_sample_test

production:
  <<: *default
  database: todo_sample_production
  username: todo_sample
  password: <%= ENV['BACKEND_DATABASE_PASSWORD'] %>
